# Generated by Django 4.2.4 on 2023-10-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('profilePicture', models.CharField(max_length=100)),
                ('isLoggedIn', models.BooleanField(default=False)),
                ('accountCreationDate', models.DateTimeField(auto_now_add=True)),
                ('lastLoginDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('foundedYear', models.PositiveIntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('userGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('memberCount', models.PositiveIntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('createdByUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupConnection',
            fields=[
                ('connectionID', models.AutoField(primary_key=True, serialize=False)),
                ('connectionDate', models.DateTimeField(auto_now_add=True)),
                ('connectionType', models.CharField(max_length=50)),
                ('userGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.usergroup')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('connectionID', models.AutoField(primary_key=True, serialize=False)),
                ('connectionDate', models.DateTimeField(auto_now_add=True)),
                ('connectionType', models.CharField(max_length=50)),
                ('userID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1ID', to='helloapp.appuser')),
                ('userID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2ID', to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillID', models.AutoField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(max_length=100)),
                ('skillLevel', models.CharField(max_length=50)),
                ('endorsementCount', models.PositiveIntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
                ('receiverUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='helloapp.appuser')),
                ('senderUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('experienceID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('employmentType', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('educationID', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('fieldOfStudy', models.CharField(max_length=100)),
                ('graduationDate', models.DateField()),
                ('activities', models.TextField()),
                ('description', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helloapp.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='userConnections',
            field=models.ManyToManyField(through='helloapp.UserConnection', to='helloapp.appuser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='userGroupConnections',
            field=models.ManyToManyField(through='helloapp.UserGroupConnection', to='helloapp.appuser'),
        ),
    ]
