envs:
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "True"
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
name: bridgeOut
region: nyc
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: josh-flatt/cs350
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: bridgeOut
  routes:
  - path: /
  run_command: |
    python manage.py migrate --no-input
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: ServerTestApp
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: josh-flatt/cs350
  name: bridgeOut
  routes:
  - path: /static
  source_dir: Application